### ISSUE TITLE
Can import package - Angular 12 support

### ISSUE THREAD

**Issue by Sandip124** [pierreavn/angular-tabler-icons#1]
![image](https://user-images.githubusercontent.com/37034590/128601935-f6f13cb8-c566-4214-a0d3-55b935ea7dfe.png)
error when npm install,

**Comment by pierreavn** [comment]
Hi,

Thank you for reporting this issue, this was due to Angular 12 support.
This should be working now, be sure to install the newest version I've published, with:
```
npm install angular-tabler-icons@1.41.3
```

Please tell me if it's working on your side
Have a good day

**Comment by Sandip124** [comment]
still same issue 😢

**Comment by pierreavn** [comment]
Can you tell me which Angular version are you using?

**Comment by Sandip124** [comment]
![image](https://user-images.githubusercontent.com/37034590/128625184-c4b50166-73a8-4994-b736-040c4dbc7556.png)


> Can you tell me which Angular version are you using?

**Comment by pierreavn** [comment]
I think this is due to your version of Node (16.3.0) that is not supporter by Angular.
Try to use Node v14 instead (see how to do here: https://subscription.packtpub.com/book/web_development/9781838558758/1/ch01lvl1sec03/installing-node-js-14-with-nvm)

**Comment by Sandip124** [comment]
i  install  node 14 and works fine , thanks 🙏🙏
