### ISSUE TITLE
Standalone components support

### ISSUE THREAD

**Issue by janschab** [pierreavn/angular-tabler-icons#109]
Hi, I'd like to provide some icons for each components, and it working with components within module, but not working in standalone component, because `TablerIconsModule.pick` method returns `ModuleWithProviders<TablerIconsModule>` and its not suited to imports in standalone components.
Solution is to create provider with pick method, and move picking from imports to providers.
I tested it in local version, but I prefer to use npm package, so I have a PR
I upgraded angular to 14 to create sample standalone component

**Comment by pierreavn** [comment]
Hi @janschab, thank you very much for you contribution!
I've just merged and deployed it to `angular-tabler-icons@2.21.1` package.
Can you give it a try?

**Comment by janschab** [comment]
thanks @pierreavn! everything works well
