### ISSUE TITLE
Release awaiting for Angular 18-19

### ISSUE THREAD

**Issue by AlexandruMM-hub** [pierreavn/angular-tabler-icons#144]
Waiting for realease for angular 18 and 19, docs are updated :D but wasn't released

**Comment by xylplm** [comment]
me too

**Comment by influcenzo** [comment]
+1

**Comment by pierreavn** [comment]
`angular-tabler-icons` version 3.22.0 has been released with Angular 18 & 19 support 🎉  
Feel free to use it with `nom install angular-tabler-icons@3.22.0`
