### ISSUE TITLE
Icons module is not a reference value

### ISSUE THREAD

**Issue by Sandip124** [pierreavn/angular-tabler-icons#2]
![image](https://user-images.githubusercontent.com/37034590/128883819-31336a2a-fe4b-4762-9efc-7ad1d1f3cb25.png)

I have install the package but when i create  module i got  this error,  and also i tried the feather icons library for angular and that is working fine so errors at all.

**Comment by rajkaran** [comment]
@Sandip124 did you found any solution to this?

**Comment by pierreavn** [comment]
Hi,

Thank you for reporting this issue.
This should be working now, be sure to install the newest version I've published, with:

```bash
npm install angular-tabler-icons@1.41.4
```

Please tell me if it's working on your side
Have a good day

**Comment by Sandip124** [comment]
i will let you know 😊
