### ISSUE TITLE
Angular 15 unsupported

### ISSUE THREAD

**Issue by miyasan31** [pierreavn/angular-tabler-icons#84]
Hi.

Thanks for the great package.

[Q] Do you plan to support this in Angular v15?

**Comment by pierreavn** [comment]
Thank you for reporting this issue.  
Support for Angular 15 has been released today!

Can you check if it works for you with the latest version:
`npm install angular-tabler-icons@1.117.1`
or
`yarn add angular-tabler-icons@1.117.1`

**Comment by miyasan31** [comment]
Great response time!!!
Got it installed with no problems!

Thank you🙏

**Comment by pierreavn** [comment]
Perfect, don’t forget to star the repo if it helped you :)
