### ISSUE TITLE
Multi provider

### ISSUE THREAD

**Issue by schabu0** [pierreavn/angular-tabler-icons#98]
Hi, I'd like to use TablerIconsModule.pick i multiple lazy modules. But I noticed that in version 1.68.1 param multiple: true is no longer preset in OptionsProvider object. I wonder why and whether it is possible to restore it.

**Comment by pierreavn** [comment]
Hi schabu0,

It was removed due to dedicated `IconsModule`, but if you need it I can restore it for sure.
I'll keep you in touch in the next days when it'll be ready.

**Comment by janschab** [comment]
thans, i did [PR](https://github.com/pierreavn/angular-tabler-icons/pull/99)

**Comment by pierreavn** [comment]
Thanks for your PR, I've just merged it and released **2.11.1** 🥳 

Can you check if it works for you with the latest version:
`npm install angular-tabler-icons@2.11.1`
or
`yarn add angular-tabler-icons@2.11.1`

**Comment by janschab** [comment]
thanks a lot, it works for me, all icons from all modules are displaying 😄
